Fix clickhouse tests (#6140)
## Summary

<!--
Ideally, there is an attached GitHub issue that will describe the "why".

If relevant, use this section to call out any additional information
you'd like to _highlight_ to the reviewer.
-->

Clickhouse tests are currently failing on main
([slack](https://highlightcorp.slack.com/archives/C02CJANPHQS/p1690479345204819)):
```
    cursor_test.go:196: 
        	Error Trace:	/home/runner/work/highlight/highlight/backend/clickhouse/cursor_test.go:196
        	Error:      	Received unexpected error:
        	            	clickhouse [Decode]:  custom serialization for column Body. not supported
        	Test:       	TestClickhouseDecode
--- FAIL: TestClickhouseDecode (0.04s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
````

I can't tell what is exactly going, but something with the [latest
tag](https://hub.docker.com/layers/clickhouse/clickhouse-server/23.7.1/images/sha256-4ee2d642df3481db1809ca632bd3f9d67b1245a75813fb2d618293d7aabed414?context=explore)
in docker hits this codepath:

https://github.com/ClickHouse/clickhouse-go/blame/main/lib/proto/block.go#L222-L230

Per the [PR](https://github.com/ClickHouse/clickhouse-go/pull/854) that
implemented this, perhaps we need to to be explicit on the column types
when we query? I've filed #6141 to figure that out.

This PR hardcodes the clickhouse version we fetch in docker. The version
is pulled from the closet tag that matches clickhouse cloud (`SELECT
version()` => `23.5.1.34446`).

## How did you test this change?

<!--
Frontend - Leave a screencast or a screenshot to visually describe the
changes.
-->

Reset go test cache: `go clean -testcache`
Rerun any clickhouse test and confirm it passes.

CI should also pass as well.


## Are there any deployment considerations?

<!--
 Backend - Do we need to consider migrations or backfilling data?
-->