fix undefined reference to navigator.storage.estimate (#5741)
## Summary

Some browsers do not define `navigator.storage.estimate`.
Check if it available first. If it is undefined, we do not know how many
elements are stored in indexeddb,
so we will trust the browser will clean up when we approach storage
limits.

## How did you test this change?

[Reflame
preview](https://preview.highlight.io/?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22variantId%22%3A%2201H3WH4AFC3CXV6XMH43P4GZWA%22%2C%22region%22%3A%22sjc%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%225740-navigatorstorageestimate-is-not-a-function-in-navigatorstorageestimate-navigatorstorageestimate-is-undefined%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D).

## Are there any deployment considerations?

No