update turbo build to correctly generate rrweb types (#4937)
## Summary

Noticed our frontend deploy is broken after updating the rrweb submodule
(not caught in local build because of turborepo caching).

https://dashboard.render.com/static/srv-bsvd5d2pp1jugm7vus70/deploys/dep-cgqocs9euhlj4o3lv7e0

```Apr 11 09:15:25 AM  highlight.run:typegen: ../client/src/index.tsx(6,48): error TS2307: Cannot find module '@highlight-run/rrweb-types' or its corresponding type declarations.
Apr 11 09:15:25 AM  highlight.run:typegen: ../client/src/index.tsx(707,24): error TS7006: Parameter '_src' implicitly has an 'any' type.
Apr 11 09:15:25 AM  highlight.run:typegen: ../client/src/workers/types.ts(1,31): error TS2307: Cannot find module '@highlight-run/rrweb-types' or its corresponding type declarations.
Apr 11 09:15:25 AM  highlight.run:typegen: ERROR: command finished with error: command (/opt/render/project/src/sdk/firstload) yarn run typegen exited (1)
```

The root cause is that the `highlight.run` `typegen` step would depend
on rrweb `prepublish`, but the rrweb `build` step would also run some
time after `prepublish`. The `build` step would wipe the `typings`
directory in rrweb containing the generated types, undoing the work of
the `prepublish` step and breaking the `highlight.run` `typegen` step.

To fix this, I'm refactoring the rrweb build steps to ensure all
packages have a `prepublish` and a `build` step that are identical,
while making our repo `turbo.json` only depend on the `typegen` and
`build` steps which we use for our own packages.

## How did you test this change?

Local build with no cache.

![Screenshot 2023-04-11 at 3 42 40
PM](https://user-images.githubusercontent.com/1351531/231304458-39e03f5c-42bb-4db4-9c43-16cce59cb423.png)


## Are there any deployment considerations?

No.